### ISSUE TITLE
Errors reading SyGuS .sy file format.

### ISSUE THREAD

**Issue by pauljurczak** [yuntongzhang/eusolver#3]
I tried a simple test `./eusolver ex5.sy` with this SyGuS file:
```
(set-logic LIA)

(synth-fun f ((x Int) (y Int)) Int
    
    ((I Int) (B Bool))

    ((I Int (x y 0 1 2 3 4 5 6 7 8 9
             (ite B I I)))
     (B Bool ((<= I I))))
)

(declare-var x Int)
(declare-var y Int)

(constraint (= (f 3 1) 3))
(constraint (= (f 2 2) 2))
(constraint (= (f 1 3) 1))
(constraint (= (f 4 4) 4))
(constraint (= (f 8 5) 9))
(constraint (= (f 7 6) 9))
(constraint (= (f 9 7) 9))
(constraint (= (f 5 8) 9))
(constraint (= (f 6 9) 9))

(check-synth)
```
and got this error:
```
  File "/home/paul/eusolver/src/parsers/parser.py", line 170, in process_synth_funcs
    [name, args_data, ret_type_data] = synth_fun_data
ValueError: too many values to unpack (expected 3)
```
This file works fine with `cvc5` solver.

**Comment by pauljurczak** [comment]
Perhaps, it was a problem with using new version of SyGuS format. I tried older version:
```
(set-logic LIA)

(synth-fun f ((x Int) (y Int)) Int
    ((Start Int (x y 4 9
             (ite StartBool Start Start)))
     (StartBool Bool ((<= Start Start))))
)

(declare-var x Int)
(declare-var y Int)

(constraint (= (f 3 1) 3))
(constraint (= (f 2 2) 2))
(constraint (= (f 1 3) 1))
(constraint (= (f 4 4) 4))
(constraint (= (f 8 5) 9))
(constraint (= (f 7 6) 9))
(constraint (= (f 9 7) 9))
(constraint (= (f 5 8) 9))
(constraint (= (f 6 9) 9))

(check-synth)
```
but this resulted in:
```
(.venv) paul@desktop:~/eusolver$ ./eusolver ex5.sy
Traceback (most recent call last):
  File "/home/paul/eusolver/src/enumerators/enumerators.py", line 325, in generate
    ret = self.factory.get_from(self.placeholder, self.size, self.generated)
  File "/home/paul/eusolver/src/enumerators/enumerators.py", line 440, in get_from
    next_expr = next(self.base_generators[(placeholder, size)])
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/paul/eusolver/src/benchmarks.py", line 441, in <module>
    test_make_solver(benchmark_files)
  File "/home/paul/eusolver/src/benchmarks.py", line 416, in test_make_solver
    make_solver(file_sexp)
  File "/home/paul/eusolver/src/benchmarks.py", line 375, in make_solver
    final_solutions = solver(*solver_args)
  File "/home/paul/eusolver/src/benchmarks.py", line 258, in std_unification_solver
    solution = next(solutions)
  File "/home/paul/eusolver/src/core/solvers.py", line 102, in solve
    unification = next(unifier_state)
  File "/home/paul/eusolver/src/unifiers/unifiers.py", line 143, in unify
    self.pred_solver.generate_more_terms()
  File "/home/paul/eusolver/src/termsolvers/termsolvers.py", line 265, in generate_more_terms
    return self._default_generate_more_terms(transform_term=None)
  File "/home/paul/eusolver/src/termsolvers/termsolvers.py", line 209, in _default_generate_more_terms
    bunch = next(bunch_generator_state)
  File "/home/paul/eusolver/src/enumerators/enumerators.py", line 506, in generate
    retval[current_index] = next(sub_generator_state)
  File "/home/paul/eusolver/src/enumerators/enumerators.py", line 254, in generate
    yield from self.actual_generator.generate()
RuntimeError: generator raised StopIteration
```
